spring:
  profiles:
    active: local

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: strongpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8081
